style = "PATH|./static/style.css"
script = "PATH|./static/script.js"
teamspeak_updater = "PATH|./static/teamspeak_updater.js"
obs_updater = "PATH|./static/obs_updater.js"
webui_script = "PATH|./static/webui.js"
teamspeak = "PATH|./static/teamspeak.html"
obs = "PATH|./static/obs.html"
webui = "PATH|./static/webui.html"